### ISSUE TITLE
Optimise extension + Change all of the code

### ISSUE THREAD

**Issue by SenpaiHunters** [kishanhitk/SnapSearch#2]
# Whole extension changes:
Refer to my comment on issue #1 .

![vscode](https://github.com/kishanhitk/SnapSearch/assets/103985728/0ee4c2b4-a191-4c54-898a-bac51aa8e1c7)

- Changed CSS styles into its own file
- Changed JS, `background.js` and `popup.js` into its own JS location
- Changed `hello.html` to `popup.html` to align with Chromium dev docs
- Optimise both `background.js` and `popup.js`
- Added support for Ecosia
- Optimise all images, and removed the second appended image inside the original folder
- Updated the formatting on all of the code
- Added a default lang to the html
- Added a viewpoint to the html
- Added a title to the html
- Re-referred everything to its new location
- Add a `.gitignore` to the codebase
- Changed base HTML look via CSS (refer to below img)

![Arc - March 03 2024 - 02 43 PM@2x](https://github.com/kishanhitk/SnapSearch/assets/103985728/5ea30f0a-c96b-44d0-a259-c988cb315dbd)

- Updated `readme.md` to remove the need of `Node.js`, as this is false, it is not needed
    - Changed the `readme.md` to further outline the install guide, changed the icon to the top of the title
    - Added all search engines to the list, Ecosia included.
    - For a visualisation, refer to the below image

![vscode](https://github.com/kishanhitk/SnapSearch/assets/103985728/ac4a8135-7764-4f9b-adef-198c71819e70)

# **Before optimisation**
Total folder size (minus `.git`): **120kb**
Total extension size (icons included): **32kb**
Total extension size (minus icons): **16kb**

# **After optimisation**
Total folder size (minus `.git`): **98kb**
Total extension size (icons included): **8kb**
Total extension size (minus icons): **5kb**

**Comment by SenpaiHunters** [comment]
[SnapSearch.zip](https://github.com/kishanhitk/SnapSearch/files/14730489/SnapSearch.zip)
New version

**Comment by kishanhitk** [comment]
Hey @SenpaiHunters thank you so much for the contribution.

The suggested changes looks very useful. Does this also fix incompatibility issue on Windows?

Also, I have added the license, so can you please open a PR with the changes?
